# Generated by Django 5.0.2 on 2024-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snitch',
            name='replies',
        ),
        migrations.AddField(
            model_name='snitch',
            name='replies',
            field=models.ManyToManyField(related_name='messages', to='projectApp.message'),
        ),
    ]
