# Generated by Django 5.0.2 on 2024-04-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_remove_snitch_replies_snitch_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snitch',
            name='snitchtext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.message'),
        ),
    ]
