# Generated by Django 5.0.2 on 2024-04-11 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0006_remove_snitch_replies_alter_snitch_title_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='snitch',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='messages', to='projectApp.message'),
        ),
        migrations.AlterField(
            model_name='snitch',
            name='Title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='reply',
        ),
    ]
