# Generated by Django 5.0.2 on 2024-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0007_snitch_replies_alter_snitch_title_delete_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snitch',
            name='topics',
        ),
        migrations.AddField(
            model_name='snitch',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='topics', to='projectApp.topics'),
        ),
    ]
