# Generated by Django 5.0.2 on 2024-04-11 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_message_reactedusers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reactedusers',
        ),
        migrations.AddField(
            model_name='message',
            name='downvotedusers',
            field=models.ManyToManyField(blank=True, related_name='downvotedusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='upvotedusers',
            field=models.ManyToManyField(blank=True, related_name='upvotedusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
