# Generated by Django 5.0.2 on 2024-04-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0011_remove_message_reactedusers_message_downvotedusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_reply',
            field=models.CharField(default='true', max_length=200),
        ),
    ]
